Add copy feature
IMGIITRoorkee/omniport-django-filemanager pull request #77
Opened 2022-12-12 16:18 UTC by mrstark14

2022-12-27 06:14 UTC, gauransh7 requested changes

2022-12-27 06:14 UTC, gauransh7 commented on views/file.py
> +            person = Person.objects.get(pk=folder.person_id)
There should be a additional check that the person is same as the request.person.
What if the destination was corresponding to a folder which is not owned by request.person.

2022-12-27 06:14 UTC, gauransh7 commented on views/folder.py
> +            person = Person.objects.get(pk=final_folder.person_id)
Same here.

2022-12-27 06:14 UTC, gauransh7 commented on views/file.py
> +            file = File.objects.get(pk=file_id)
Add a check for the file ownership. (request.person==file.person)

2023-01-12 04:13 UTC, mrstark14 commented on views/file.py
> +            person = Person.objects.get(pk=folder.person_id)
at line 296, the final folder has check_object_permissions

2023-03-28 13:48 UTC, merged